# Generated by Django 5.2.4 on 2025-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_deleted_by_property_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
