# Generated by Django 5.2.4 on 2025-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_agentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
