# Generated by Django 5.2.4 on 2025-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
