# Generated by Django 5.2.4 on 2025-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminprofile_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('HR', 'Human Resources'), ('IT', 'Information Technology')], max_length=100, null=True),
        ),
    ]
